[2024-10-08T16:02:33.950+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-08T16:02:33.993+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_database.test_postgres_connection manual__2024-10-08T16:02:31.974767+00:00 [queued]>
[2024-10-08T16:02:34.008+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_database.test_postgres_connection manual__2024-10-08T16:02:31.974767+00:00 [queued]>
[2024-10-08T16:02:34.011+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-08T16:02:34.042+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): test_postgres_connection> on 2024-10-08 16:02:31.974767+00:00
[2024-10-08T16:02:34.051+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1469) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T16:02:34.054+0000] {standard_task_runner.py:63} INFO - Started process 1471 to run task
[2024-10-08T16:02:34.054+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_database', 'test_postgres_connection', 'manual__2024-10-08T16:02:31.974767+00:00', '--job-id', '3853', '--raw', '--subdir', 'DAGS_FOLDER/update.py', '--cfg-path', '/tmp/tmpd_3zz74x']
[2024-10-08T16:02:34.057+0000] {standard_task_runner.py:91} INFO - Job 3853: Subtask test_postgres_connection
[2024-10-08T16:02:34.113+0000] {task_command.py:426} INFO - Running <TaskInstance: update_database.test_postgres_connection manual__2024-10-08T16:02:31.974767+00:00 [running]> on host 1fee8bc549a8
[2024-10-08T16:02:34.279+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_database' AIRFLOW_CTX_TASK_ID='test_postgres_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T16:02:31.974767+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T16:02:31.974767+00:00'
[2024-10-08T16:02:34.285+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-08T16:02:34.305+0000] {logging_mixin.py:188} INFO - Connection to PostgreSQL DB successful
[2024-10-08T16:02:34.327+0000] {logging_mixin.py:188} INFO - Data exported to /opt/***/dags/csvs/date_csv/last_date.csv successfully.
[2024-10-08T16:02:34.329+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-08T16:02:34.334+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-08T16:02:34.359+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=update_database, task_id=test_postgres_connection, run_id=manual__2024-10-08T16:02:31.974767+00:00, execution_date=20241008T160231, start_date=20241008T160233, end_date=20241008T160234
[2024-10-08T16:02:34.432+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-08T16:02:34.483+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T16:02:34.485+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
