[2024-09-27T12:42:24.099+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-27T12:42:24.134+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: intialization_database.merge_transform_football_data_task manual__2024-09-27T12:42:19.276259+00:00 [queued]>
[2024-09-27T12:42:24.143+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: intialization_database.merge_transform_football_data_task manual__2024-09-27T12:42:19.276259+00:00 [queued]>
[2024-09-27T12:42:24.143+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-27T12:42:24.157+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): merge_transform_football_data_task> on 2024-09-27 12:42:19.276259+00:00
[2024-09-27T12:42:24.167+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=274) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-27T12:42:24.169+0000] {standard_task_runner.py:63} INFO - Started process 276 to run task
[2024-09-27T12:42:24.169+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'intialization_database', 'merge_transform_football_data_task', 'manual__2024-09-27T12:42:19.276259+00:00', '--job-id', '2755', '--raw', '--subdir', 'DAGS_FOLDER/initialization.py', '--cfg-path', '/tmp/tmp8c_brazd']
[2024-09-27T12:42:24.170+0000] {standard_task_runner.py:91} INFO - Job 2755: Subtask merge_transform_football_data_task
[2024-09-27T12:42:24.222+0000] {task_command.py:426} INFO - Running <TaskInstance: intialization_database.merge_transform_football_data_task manual__2024-09-27T12:42:19.276259+00:00 [running]> on host 3439da570e34
[2024-09-27T12:42:24.329+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='intialization_database' AIRFLOW_CTX_TASK_ID='merge_transform_football_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T12:42:19.276259+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-27T12:42:19.276259+00:00'
[2024-09-27T12:42:24.330+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-27T12:42:24.337+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-27T12:42:24.338+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/helpers_initialization_dag/football_data_merging_transforming_csvs_fl.py", line 42, in football_data_merging_transforming_csvs_fl
    df_after_nineties = pd.concat(dataframes, ignore_index=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 380, in concat
    op = _Concatenator(
         ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 443, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/concat.py", line 539, in _clean_keys_and_objs
    raise ValueError("All objects passed were None")
ValueError: All objects passed were None
[2024-09-27T12:42:24.353+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=intialization_database, task_id=merge_transform_football_data_task, run_id=manual__2024-09-27T12:42:19.276259+00:00, execution_date=20240927T124219, start_date=20240927T124224, end_date=20240927T124224
[2024-09-27T12:42:24.370+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2755 for task merge_transform_football_data_task (All objects passed were None; 276)
[2024-09-27T12:42:24.384+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-27T12:42:24.412+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-27T12:42:24.414+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
