[2024-10-01T16:36:08.455+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-01T16:36:08.490+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: intialization_database.merge_transform_football_data_task manual__2024-10-01T16:35:55.875079+00:00 [queued]>
[2024-10-01T16:36:08.499+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: intialization_database.merge_transform_football_data_task manual__2024-10-01T16:35:55.875079+00:00 [queued]>
[2024-10-01T16:36:08.500+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-01T16:36:08.517+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): merge_transform_football_data_task> on 2024-10-01 16:35:55.875079+00:00
[2024-10-01T16:36:08.526+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5059) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-01T16:36:08.528+0000] {standard_task_runner.py:63} INFO - Started process 5061 to run task
[2024-10-01T16:36:08.528+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'intialization_database', 'merge_transform_football_data_task', 'manual__2024-10-01T16:35:55.875079+00:00', '--job-id', '3041', '--raw', '--subdir', 'DAGS_FOLDER/initialization.py', '--cfg-path', '/tmp/tmpss_55890']
[2024-10-01T16:36:08.530+0000] {standard_task_runner.py:91} INFO - Job 3041: Subtask merge_transform_football_data_task
[2024-10-01T16:36:08.584+0000] {task_command.py:426} INFO - Running <TaskInstance: intialization_database.merge_transform_football_data_task manual__2024-10-01T16:35:55.875079+00:00 [running]> on host f8103d9b7858
[2024-10-01T16:36:08.705+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='intialization_database' AIRFLOW_CTX_TASK_ID='merge_transform_football_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T16:35:55.875079+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-01T16:35:55.875079+00:00'
[2024-10-01T16:36:08.708+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-01T16:36:09.884+0000] {warnings.py:112} WARNING - /opt/***/dags/helpers_initialization_dag/football_data_merging_transforming_csvs_fl.py:94: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_99_00_00['Date'] = df_99_00_00['Date'].apply(fix_date_format_after_nineties)

[2024-10-01T16:36:09.912+0000] {warnings.py:112} WARNING - /opt/***/dags/helpers_initialization_dag/football_data_merging_transforming_csvs_fl.py:99: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_99_00_99['Date'] = df_99_00_99['Date'].apply(fix_date_format)

[2024-10-01T16:36:09.954+0000] {warnings.py:112} WARNING - /opt/***/dags/helpers_initialization_dag/football_data_merging_transforming_csvs_fl.py:113: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_concatenated = df_concatenated.applymap(lambda x: x.strip() if isinstance(x, str) else x)

[2024-10-01T16:36:10.050+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-01T16:36:10.051+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/helpers_initialization_dag/football_data_merging_transforming_csvs_fl.py", line 117, in football_data_merging_transforming_csvs_fl
    df_concatenated.to_csv('/opt/airflow/dags/csvs/first_load_csvs/football_data_merged_transformed_football_data.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/dags/csvs/first_load_csvs/football_data_merged_transformed_football_data.csv'
[2024-10-01T16:36:10.092+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=intialization_database, task_id=merge_transform_football_data_task, run_id=manual__2024-10-01T16:35:55.875079+00:00, execution_date=20241001T163555, start_date=20241001T163608, end_date=20241001T163610
[2024-10-01T16:36:10.117+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3041 for task merge_transform_football_data_task ([Errno 13] Permission denied: '/opt/airflow/dags/csvs/first_load_csvs/football_data_merged_transformed_football_data.csv'; 5061)
[2024-10-01T16:36:10.148+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-01T16:36:10.163+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-10-01T16:36:10.187+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T16:36:10.190+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
