[2024-10-01T15:25:21.160+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-01T15:25:21.186+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: intialization_database.copy_data_to_staging_table_fl manual__2024-10-01T15:19:25.731918+00:00 [queued]>
[2024-10-01T15:25:21.195+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: intialization_database.copy_data_to_staging_table_fl manual__2024-10-01T15:19:25.731918+00:00 [queued]>
[2024-10-01T15:25:21.197+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-10-01T15:25:21.214+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): copy_data_to_staging_table_fl> on 2024-10-01 15:19:25.731918+00:00
[2024-10-01T15:25:21.221+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4124) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-01T15:25:21.223+0000] {standard_task_runner.py:63} INFO - Started process 4126 to run task
[2024-10-01T15:25:21.223+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'intialization_database', 'copy_data_to_staging_table_fl', 'manual__2024-10-01T15:19:25.731918+00:00', '--job-id', '3027', '--raw', '--subdir', 'DAGS_FOLDER/initialization.py', '--cfg-path', '/tmp/tmpgyf3u22b']
[2024-10-01T15:25:21.224+0000] {standard_task_runner.py:91} INFO - Job 3027: Subtask copy_data_to_staging_table_fl
[2024-10-01T15:25:21.275+0000] {task_command.py:426} INFO - Running <TaskInstance: intialization_database.copy_data_to_staging_table_fl manual__2024-10-01T15:19:25.731918+00:00 [running]> on host f8103d9b7858
[2024-10-01T15:25:21.377+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='intialization_database' AIRFLOW_CTX_TASK_ID='copy_data_to_staging_table_fl' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T15:19:25.731918+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-01T15:19:25.731918+00:00'
[2024-10-01T15:25:21.379+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-01T15:25:21.380+0000] {sql.py:276} INFO - Executing: COPY scottish_premiership.staging_table_fl
FROM '/opt/***/dags/csvs/first_load_csvs/all_sources_merged_transformed.csv'
DELIMITER ','
CSV HEADER;
[2024-10-01T15:25:21.390+0000] {base.py:84} INFO - Using connection ID 'football_scotland_connection' for task execution.
[2024-10-01T15:25:21.401+0000] {base.py:84} INFO - Using connection ID 'football_scotland_connection' for task execution.
[2024-10-01T15:25:21.406+0000] {sql.py:487} INFO - Running statement: COPY scottish_premiership.staging_table_fl
FROM '/opt/***/dags/csvs/first_load_csvs/all_sources_merged_transformed.csv'
DELIMITER ','
CSV HEADER;, parameters: None
[2024-10-01T15:25:21.408+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-01T15:25:21.409+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedFile: could not open file "/opt/***/dags/csvs/first_load_csvs/all_sources_merged_transformed.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

[2024-10-01T15:25:21.420+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=intialization_database, task_id=copy_data_to_staging_table_fl, run_id=manual__2024-10-01T15:19:25.731918+00:00, execution_date=20241001T151925, start_date=20241001T152521, end_date=20241001T152521
[2024-10-01T15:25:21.435+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3027 for task copy_data_to_staging_table_fl (could not open file "/opt/***/dags/csvs/first_load_csvs/all_sources_merged_transformed.csv" for reading: No such file or directory
HINT:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
; 4126)
[2024-10-01T15:25:21.477+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-01T15:25:21.495+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T15:25:21.497+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
