[2024-10-01T16:37:54.211+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-01T16:37:54.279+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: intialization_database.merge_transform_all_sources manual__2024-10-01T16:37:12.814136+00:00 [queued]>
[2024-10-01T16:37:54.310+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: intialization_database.merge_transform_all_sources manual__2024-10-01T16:37:12.814136+00:00 [queued]>
[2024-10-01T16:37:54.312+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-01T16:37:54.355+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): merge_transform_all_sources> on 2024-10-01 16:37:12.814136+00:00
[2024-10-01T16:37:54.372+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=5095) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-01T16:37:54.377+0000] {standard_task_runner.py:63} INFO - Started process 5097 to run task
[2024-10-01T16:37:54.379+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'intialization_database', 'merge_transform_all_sources', 'manual__2024-10-01T16:37:12.814136+00:00', '--job-id', '3046', '--raw', '--subdir', 'DAGS_FOLDER/initialization.py', '--cfg-path', '/tmp/tmp_1irwzdm']
[2024-10-01T16:37:54.382+0000] {standard_task_runner.py:91} INFO - Job 3046: Subtask merge_transform_all_sources
[2024-10-01T16:37:54.504+0000] {task_command.py:426} INFO - Running <TaskInstance: intialization_database.merge_transform_all_sources manual__2024-10-01T16:37:12.814136+00:00 [running]> on host f8103d9b7858
[2024-10-01T16:37:54.796+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='intialization_database' AIRFLOW_CTX_TASK_ID='merge_transform_all_sources' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T16:37:12.814136+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-01T16:37:12.814136+00:00'
[2024-10-01T16:37:54.799+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-01T16:37:56.705+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-01T16:37:56.706+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/helpers_initialization_dag/all_sources_merged_transformed_fl.py", line 19, in all_sources_merged_transformed_fl
    football_data_sofascore = pd.merge(football_data, sofascore, how='left', on=['game_date', 'hometeam'])
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 169, in merge
    op = _MergeOperation(
         ^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 791, in __init__
    ) = self._get_merge_keys()
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py", line 1287, in _get_merge_keys
    left_keys.append(left._get_label_or_level_values(lk))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 1844, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'game_date'
[2024-10-01T16:37:56.736+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=intialization_database, task_id=merge_transform_all_sources, run_id=manual__2024-10-01T16:37:12.814136+00:00, execution_date=20241001T163712, start_date=20241001T163754, end_date=20241001T163756
[2024-10-01T16:37:56.757+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3046 for task merge_transform_all_sources ('game_date'; 5097)
[2024-10-01T16:37:56.808+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-01T16:37:56.822+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-10-01T16:37:56.852+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-01T16:37:56.856+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
