[2024-10-08T14:01:15.495+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: update_database.delete_container_image manual__2024-10-08T14:01:12.410452+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
