[2024-10-08T14:29:29.165+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-08T14:29:29.223+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_database.pull_docker_image manual__2024-10-08T14:29:23.522255+00:00 [queued]>
[2024-10-08T14:29:29.245+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_database.pull_docker_image manual__2024-10-08T14:29:23.522255+00:00 [queued]>
[2024-10-08T14:29:29.249+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-08T14:29:29.289+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): pull_docker_image> on 2024-10-08 14:29:23.522255+00:00
[2024-10-08T14:29:29.300+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=137) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T14:29:29.303+0000] {standard_task_runner.py:63} INFO - Started process 139 to run task
[2024-10-08T14:29:29.302+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_database', 'pull_docker_image', 'manual__2024-10-08T14:29:23.522255+00:00', '--job-id', '3837', '--raw', '--subdir', 'DAGS_FOLDER/update.py', '--cfg-path', '/tmp/tmpzxx0qcqf']
[2024-10-08T14:29:29.304+0000] {standard_task_runner.py:91} INFO - Job 3837: Subtask pull_docker_image
[2024-10-08T14:29:29.379+0000] {task_command.py:426} INFO - Running <TaskInstance: update_database.pull_docker_image manual__2024-10-08T14:29:23.522255+00:00 [running]> on host 1fee8bc549a8
[2024-10-08T14:29:29.516+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_database' AIRFLOW_CTX_TASK_ID='pull_docker_image' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T14:29:23.522255+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T14:29:23.522255+00:00'
[2024-10-08T14:29:29.518+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-08T14:29:29.520+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-08T14:29:29.521+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'docker pull kostasmitalloulis/sofascoe_scraper_image_up:latest']
[2024-10-08T14:29:29.545+0000] {subprocess.py:86} INFO - Output:
[2024-10-08T14:29:31.483+0000] {subprocess.py:93} INFO - latest: Pulling from kostasmitalloulis/sofascoe_scraper_image_up
[2024-10-08T14:29:31.486+0000] {subprocess.py:93} INFO - Digest: sha256:b006a03f459412ff1f832f038b08ce4a3c259b5f5216e68ba1f72d9e2656c479
[2024-10-08T14:29:31.487+0000] {subprocess.py:93} INFO - Status: Image is up to date for kostasmitalloulis/sofascoe_scraper_image_up:latest
[2024-10-08T14:29:31.492+0000] {subprocess.py:93} INFO - docker.io/kostasmitalloulis/sofascoe_scraper_image_up:latest
[2024-10-08T14:29:31.495+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-08T14:29:31.497+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-08T14:29:31.553+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=update_database, task_id=pull_docker_image, run_id=manual__2024-10-08T14:29:23.522255+00:00, execution_date=20241008T142923, start_date=20241008T142929, end_date=20241008T142931
[2024-10-08T14:29:31.687+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-08T14:29:31.709+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-08T14:29:31.809+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
