[2024-10-03T11:35:15.072+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-03T11:35:15.161+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: intialization_database.merge_transform_all_sources manual__2024-10-03T11:34:38.301905+00:00 [queued]>
[2024-10-03T11:35:15.194+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: intialization_database.merge_transform_all_sources manual__2024-10-03T11:34:38.301905+00:00 [queued]>
[2024-10-03T11:35:15.198+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-10-03T11:35:15.254+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): merge_transform_all_sources> on 2024-10-03 11:34:38.301905+00:00
[2024-10-03T11:35:15.280+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=458) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-03T11:35:15.285+0000] {standard_task_runner.py:63} INFO - Started process 460 to run task
[2024-10-03T11:35:15.287+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'intialization_database', 'merge_transform_all_sources', 'manual__2024-10-03T11:34:38.301905+00:00', '--job-id', '3741', '--raw', '--subdir', 'DAGS_FOLDER/initialization.py', '--cfg-path', '/tmp/tmpejh_oyds']
[2024-10-03T11:35:15.295+0000] {standard_task_runner.py:91} INFO - Job 3741: Subtask merge_transform_all_sources
[2024-10-03T11:35:15.453+0000] {task_command.py:426} INFO - Running <TaskInstance: intialization_database.merge_transform_all_sources manual__2024-10-03T11:34:38.301905+00:00 [running]> on host 7d10ea254acc
[2024-10-03T11:35:15.776+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='intialization_database' AIRFLOW_CTX_TASK_ID='merge_transform_all_sources' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T11:34:38.301905+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-03T11:34:38.301905+00:00'
[2024-10-03T11:35:15.779+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-03T11:35:20.635+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-03T11:35:20.643+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/helpers_initialization_dag/all_sources_merged_transformed_fl.py", line 495, in all_sources_merged_transformed_fl
    football_data_sofascore_only_general_stats_match_reports.to_csv('/opt/airflow/dags/csvs/first_load_csvs/all_sources_merged_transformed.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
PermissionError: [Errno 13] Permission denied: '/opt/airflow/dags/csvs/first_load_csvs/all_sources_merged_transformed.csv'
[2024-10-03T11:35:20.827+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=intialization_database, task_id=merge_transform_all_sources, run_id=manual__2024-10-03T11:34:38.301905+00:00, execution_date=20241003T113438, start_date=20241003T113515, end_date=20241003T113520
[2024-10-03T11:35:20.877+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3741 for task merge_transform_all_sources ([Errno 13] Permission denied: '/opt/airflow/dags/csvs/first_load_csvs/all_sources_merged_transformed.csv'; 460)
[2024-10-03T11:35:20.954+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-03T11:35:20.974+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py:1297: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2024-10-03T11:35:21.009+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-03T11:35:21.018+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
