[2024-09-27T12:38:51.509+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-27T12:38:51.561+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: intialization_database.merge_transform_fbref_only_general_stats_of_each_match manual__2024-09-27T12:35:10.037956+00:00 [queued]>
[2024-09-27T12:38:51.584+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: intialization_database.merge_transform_fbref_only_general_stats_of_each_match manual__2024-09-27T12:35:10.037956+00:00 [queued]>
[2024-09-27T12:38:51.585+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-27T12:38:51.618+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): merge_transform_fbref_only_general_stats_of_each_match> on 2024-09-27 12:35:10.037956+00:00
[2024-09-27T12:38:51.639+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=226) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-27T12:38:51.644+0000] {standard_task_runner.py:63} INFO - Started process 228 to run task
[2024-09-27T12:38:51.653+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'intialization_database', 'merge_transform_fbref_only_general_stats_of_each_match', 'manual__2024-09-27T12:35:10.037956+00:00', '--job-id', '2753', '--raw', '--subdir', 'DAGS_FOLDER/initialization.py', '--cfg-path', '/tmp/tmpvoj3yoy4']
[2024-09-27T12:38:51.655+0000] {standard_task_runner.py:91} INFO - Job 2753: Subtask merge_transform_fbref_only_general_stats_of_each_match
[2024-09-27T12:38:51.741+0000] {task_command.py:426} INFO - Running <TaskInstance: intialization_database.merge_transform_fbref_only_general_stats_of_each_match manual__2024-09-27T12:35:10.037956+00:00 [running]> on host 3439da570e34
[2024-09-27T12:38:51.963+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='intialization_database' AIRFLOW_CTX_TASK_ID='merge_transform_fbref_only_general_stats_of_each_match' AIRFLOW_CTX_EXECUTION_DATE='2024-09-27T12:35:10.037956+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-27T12:35:10.037956+00:00'
[2024-09-27T12:38:51.970+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-27T12:38:51.972+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-27T12:38:51.974+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/helpers_initialization_dag/fbref_only_general_stats_of_each_match_merging_transforming_fl.py", line 12, in fbref_only_general_stats_of_each_match_merging_transforming_fl
    csv_files_only_general_stats = [file for file in os.listdir(path_for_all_csvs_only_general_stats) if file.endswith('.csv')]
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../csvs/first_load_csvs/fbref_csvs/only_general_stats_of_each_match/'
[2024-09-27T12:38:52.002+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=intialization_database, task_id=merge_transform_fbref_only_general_stats_of_each_match, run_id=manual__2024-09-27T12:35:10.037956+00:00, execution_date=20240927T123510, start_date=20240927T123851, end_date=20240927T123852
[2024-09-27T12:38:52.029+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2753 for task merge_transform_fbref_only_general_stats_of_each_match ([Errno 2] No such file or directory: '../csvs/first_load_csvs/fbref_csvs/only_general_stats_of_each_match/'; 228)
[2024-09-27T12:38:52.066+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-27T12:38:52.117+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-27T12:38:52.119+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
