[2024-10-03T11:09:52.974+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: intialization_database.data_insert_dim_tables_fl manual__2024-10-03T11:08:10.204482+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
