[2024-10-03T11:10:38.385+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: intialization_database.merge_transform_fbref_only_general_stats_of_each_match manual__2024-10-03T11:05:37.185882+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
